import sys
from pathlib import Path

import numpy as np
import pytest

# The app modules live in the repo root (no package), make them importable.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


@pytest.fixture(scope="session")
def unit_cube():
    """Tet mesh of [0,1]^3 generated by netgen: (points, tets, boundary tris), 0-based."""
    from netgen.csg import unit_cube as geo
    m = geo.GenerateMesh(maxh=0.4)
    P = np.array([[p[0], p[1], p[2]] for p in m.Points()])
    T = np.array([[int(v.nr) - 1 for v in e.vertices] for e in m.Elements3D()])
    F = np.array([[int(v.nr) - 1 for v in e.vertices] for e in m.Elements2D()])
    return P, T, F
